### ISSUE TITLE
Newer Emacs

### ISSUE THREAD

**Issue by huyz** [neil-smithline-elisp/EmacsClient.app#2]
Since the publication of this app, I've seen a couple of GUI Emacs apps that are in my opinion better than Aquamacs, which I no longer use: the distribution Emacs for Mac OS X client and https://github.com/railwaycat/emacs-mac-port

Can we have access to the source code so that it can be recompiled to support these Emacses instead?

**Comment by huyz** [comment]
Until we get the source code from the author, a workaround is a symlink fro `/Applications/Aquamacs.app` to `/Applications/Emacs.app`

**Comment by jpcirrus** [comment]
The app is an AppleScript application which can be opened in AppleScript Editor and modified. You can also modify the `Info.plist` in the app bundle with any text editor.

**Comment by huyz** [comment]
Thanks
